language: node_js
node_js:
- node
services:
- mongodb
addons:
  apt:
    sources:
    - mongodb-3.2-precise
    packages:
    - mongodb-org-server
before_deploy:
- npm run build
deploy:
  provider: npm
  email: anthony.kerz@gmail.com
  skip_cleanup: true
  on:
    branch: master
    condition: "-z $TRAVIS_TAG"
  api_key:
    secure: V+KCg0EwtV58jSIcUSvoU2OqiGzqIRaBGCoQ9x7NjaoWYeapWmGkRPZxizKgZ4Shhl+GLun4dQHldZkOxVaCGmo4rg2dPO1+UwWE73mpxrz5weNkKjV3MnY4pFhWTBoYCtA4/uCQrkfEkLYhvj0grpSCBLOoAywLLGpRkm9fZs26Di0OAcAw+5rizEuzO0BcSjc4VlWEsRfhZTMvj9sqMyDoIocvuj34W57LNENhrFlWFBNyPMMoW0byPrubcNGphWCaYzzMvwFLuwTCfG42ERO/mzxBP3QqRjTKPJxho3fOnNM0UtluJ6a2ta82ACVjAxXMsPV+KMSZjFO+3kMiJNyZRJNjP5CwQoK5NXdsZtT/yRztnoxeh9P0p+W97tbtoqAav7VwIvzWrtKF6UGpgC3KcjR17ntwEXqSSwxO8X0TBNDbJv55aobjaq0W6TVvvKM3s8d398aa4VWG9pw3oozPLj3LZkcAzmnSALvn/jj7QSUvd4aT7SCiOlu7+jrWDY4dvc5dxxGn8MBMceZsboB3cFpl4kTJ63LwrRQJKZqOAKEYp/qlfYyMFnCYGzz8NwqQ4dR2NzuhLFqNeOYecMT2KCAXG8wIRyiInRHjNhhGs8yqKs6F825UrHgiM04Qd9qHXgt4Afu57P8k+WFDnay3+KV/MdkoVA/Q8kUJ44U=
