language: node_js
node_js:
- node
services:
- mongodb
addons:
  apt:
    sources:
    - mongodb-3.2-precise
    packages:
    - mongodb-org-server
before_deploy:
- npm run build
deploy:
  provider: npm
  email: anthony.kerz@gmail.com
  skip_cleanup: true
  on:
    branch: master
    condition: "-z $TRAVIS_TAG"
  api_key:
    secure: uU/CoJTRPz2sV/UVxUYei0WF1e4Mi/AfTWpfKcXjD2wmpiyRC6JpxUCq+Je4G2jXRdPU11wAv6/lfY1eGX6Qeat/ITlgGNu6/ZkAtPB6BI5d4qZk12S7b/wTp6UdobQlzKUUIskRFGAhq4IV6dUnflMJLugPzGeEk8ejz+OsaBvp1K6bIBoIQsSOZQjJ3vKh+BOrtYTh92HSH0UPd3NOCd2ZEf19luLushIjnqRK32hMpGq46N9rxVEQqbmwtygg0t2icfAYqMGrJKEYp7PbrFG5TOBDkzaPWqatDDmR79KEhPHpTriQP1YdherKOWS9qjhOr12KC6+x9fu8ed3DhsaTiLXi2a+6FUyqqM0FYOW7j82oobmBGxniY2Sw5fn7RKl/D9Koy5KXYtCvtT+Dyu0MuQfY13NmL9TVe8NlSwaPcWsxmN+PQyLGyMX4sQw/K3WWDhmxQy6rB9mPIRL5+JohMJFd9/Oc6RjoA3qpOv5rTRuq1clMnw17sAxAm8lYT5TbPHSFCICXfTXeiicfWyQFQebhubQq0CogtajXdrR3A1MiGlqvwwXky8NVVCQm+WNHJgW90VytlXqoMYzTwkhQpPbonWVouvwuuEM2KgldgtUZGIAdvtfZ90aKY4/tAYVKJzdMsfbmukCf0/vG/tC3ouwLoi7mzVe3PKCc4EM=
